export const PROVIDER_TEMPLATES = [
  {
    name: "DBS PayLah!",
    description: "DBS digital wallet",
    icon: "dbs-paylah.png", // or text/emoji
    type: "expense",
    defaultConfig: {
      gmailQuery: `subject:(Transaction Alerts) "paylah.alert@dbs.com"`,
      bodyStartMarker: "Transaction Ref:",
      bodyEndMarker: "To view your transactions",
      merchantRegex: "^to:\\s*([a-z0-9 .&()-]+)$",
      merchantGroupIndex: 1,
      amountRegex: "(SGD)\\s?([\\d,.]+)",
      currencyGroupIndex: 0,
      amountGroupIndex: 2,
      dateRegex:
        "Date\\s*&\\s*Time:\\s*(\\d{1,2}\\s+[A-Za-z]+)\\s+(\\d{2}:\\d{2})\\s+\\(([A-Z]+)\\)",
      dateGroupIndex: 1,
      timeGroupIndex: 2,
      timezoneGroupIndex: 3,
    },
  },
  {
    name: "DBS (incoming transfer)",
    description: "PayNow, FAST, etc",
    icon: "📨",
    type: "income",
    defaultConfig: {
      gmailQuery: `subject:(digibank Alerts - You've received a transfer) "ibanking.alert@dbs.com"`,
      bodyStartMarker: "Transaction Ref:",
      bodyEndMarker: "Thank you for banking with us",
      merchantRegex: "\\*?\\s*From\\s*:\\s*\\*?\\s*([^\\n]+)",
      merchantGroupIndex: 1,
      amountRegex: "You have received\\s+(SGD)\\s+([\\d,.]+)\\s+via",
      currencyGroupIndex: 1,
      amountGroupIndex: 2,
      dateRegex:
        "(\\d{1,2}[ \\t]+[A-Za-z]{3}(?:[ \\t]+\\d{4})?)[ \\t]+(\\d{1,2}:\\d{2})(?:[ \\t]+\\(?([A-Z]{2,5}|UTC[+-]\\d{1,2}(?::?\\d{2})?|[+-]\\d{2}:?\\d{2})\\)?)?",
      dateGroupIndex: 1,
      timeGroupIndex: 2,
      timezoneGroupIndex: 3,
    },
  },
  {
    name: "YouTrip",
    description: "Multi-currency wallet",
    icon: "youtrip.png",
    type: "expense",
    defaultConfig: {
      gmailQuery: `subject:online purchases "noreply@you.co"`,
      bodyStartMarker: "Time (UTC+8)",
      bodyEndMarker: "full transaction history",
      merchantRegex: "^(.+)(?=[A-Z]{3}\\s+[\\d,.]+)",
      merchantGroupIndex: 1,
      amountRegex: "([A-Z]{3})\\s+([\\d,.]+)",
      currencyGroupIndex: 1,
      amountGroupIndex: 2,
    },
  },
];
